### ISSUE TITLE
TODOを作成するエンドポイントのOpenAPI定義を作成する

### ISSUE THREAD

**Issue by lemo-nade-room** [lemo-nade-room/es-cqrs-example-api#2]
# 概要

`POST /api/todo` エンドポイントの仕様を OpenAPI 3.0 形式で定義する。

---

# 受け入れ条件

1. **paths 定義**

   * `paths["/api/todo"].post` が存在する

2. **requestBody**

   * `application/json` を許容
   * スキーマは空オブジェクト（プロパティ不要）

3. **responses**

   * ステータス `201`
   * `content: application/json` に以下スキーマ参照

     ```yaml
     components:
       schemas:
         TodoIdResponse:
           type: object
           properties:
             id:
               type: string
               format: uuid
           required:
             - id
     ```

4. **components**

   * `schemas.TodoIdResponse` を上記定義で追加

5. **検証**

   * `swagger-cli validate openapi.yaml` 等でエラーなし

6. **ドキュメント配置**

   * 既存の `openapi.yaml` （または `openapi.json`）にコミット

7. **動作確認**

   * Swagger UI でエンドポイントが表示され、`201`／`{"id":"..."}` を返すこと
