### ISSUE TITLE
Todo取得API (GET /api/todo/{id}) のOpenAPI定義を作成する

### ISSUE THREAD

**Issue by lemo-nade-room** [lemo-nade-room/es-cqrs-example-api#5]
### 概要

issue #1 「Todoを作成できるようにする」のsub-issueとして、`GET /api/todo/{id}` APIエンドポイントのOpenAPI定義を作成します。このエンドポイントは指定されたIDのTodoを取得するために必要です。

### 要件

1. **OpenAPI仕様**
   * OpenAPI 3.0形式でエンドポイントを定義
   * 既存のOpenAPI定義ファイルに追加する形で実装

2. **エンドポイント定義内容**
   * パス: `GET /api/todo/{id}`
   * パスパラメータ: `id` (UUID形式)
   * レスポンス:
     * `200 OK`: 成功レスポンス（Todo情報を含む）
     * `404 Not Found`: Todoが存在しない場合
     * `400 Bad Request`: 無効なUUID形式の場合

3. **レスポンススキーマ**
   * 成功時（200）:
     ```yaml
     type: object
     properties:
       id:
         type: string
         format: uuid
       title:
         type: string
       description:
         type: string
     required:
       - id
       - title
       - description
     ```
   * エラー時（404, 400）:
     ```yaml
     type: object
     properties:
       error:
         type: string
     required:
       - error
     ```

4. **受け入れ条件**
   * OpenAPI定義が正しく記述されている
   * API定義がSwaggerUIなどでレンダリングできる
   * パラメータとレスポンスの型が適切に定義されている

### 関連issue
* 親issue: #1
* 関連issue: #4 (Todo作成Web APIのテストを記述する)
